### ISSUE TITLE
Risk score logic explanation

### ISSUE THREAD

**Issue by kadamsolanki** [protectai/llm-guard#138] opened 2024-05-15 09:49 UTC
Hey, can anyone explain me the logic of risk score calculation in toxicity scanner in input scanner, as the formula in util does not give justice to the model generated scores. 

If possible please provide a detailed explanation behind adding risk_score as a metric/indicator.

Thanks, 
Kadam

**Comment by asofter** [comment] 2024-05-15 10:06
Hey @kadamsolanki , thanks for reaching out. 

We use threshold configured and only calculate the risk score if it's above that threshold. Then the risk score is basically how far above the confidence score from the threshold.

Hope it makes sense

**Comment by asofter** [comment] 2024-05-16 07:53
I see, your use-case is sentence-level matching instead of overall text. Do you mean something which provides avg score across all sentences instead of the highest?

**Comment by asofter** [comment] 2024-07-29 07:05
Marking as duplicate of https://github.com/protectai/llm-guard/issues/111

**Closed by asofter** 2024-07-29 07:05 UTC
